export const exampleData = [
	{
		name: "Grilled Steak",
		description: "Juicy grilled steak cooked to perfection.",
		category: "meat",
		subcategory: "",
		size: [
			{ quantity: 1, price: 12.99 },
			{ quantity: 2, price: 24.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/steak.jpg",
			alt: "Grilled steak",
		},
	},
	{
		name: "Roast Chicken",
		description: "Tender roast chicken with herbs.",
		category: "meat",
		subcategory: "",
		size: [
			{ quantity: 1, price: 11.99 },
			{ quantity: 2, price: 22.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/roast_chicken.jpg",
			alt: "Roast chicken",
		},
	},
	{
		name: "Beef Kebab",
		description: "Spiced beef kebabs grilled on skewers.",
		category: "meat",
		subcategory: "",
		size: [
			{ quantity: 1, price: 10.99 },
			{ quantity: 2, price: 21.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/beef_kebab.jpg",
			alt: "Beef kebab",
		},
	},
	{
		name: "Lamb Chops",
		description: "Grilled lamb chops with rosemary.",
		category: "meat",
		subcategory: "",
		size: [
			{ quantity: 1, price: 14.99 },
			{ quantity: 2, price: 28.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/lamb_chops.jpg",
			alt: "Lamb chops",
		},
	},
	{
		name: "Turkey Schnitzel",
		description: "Crispy breaded turkey schnitzel.",
		category: "meat",
		subcategory: "",
		size: [
			{ quantity: 1, price: 9.99 },
			{ quantity: 2, price: 19.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/turkey_schnitzel.jpg",
			alt: "Turkey schnitzel",
		},
	},
	{
		name: "Cheese Lasagna",
		description: "Classic Italian lasagna with rich cheese and tomato sauce.",
		category: "dairy",
		subcategory: "",
		size: [
			{ quantity: 1, price: 9.99 },
			{ quantity: 2, price: 18.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/cheese_lasagna.jpg",
			alt: "Cheese lasagna",
		},
	},
	{
		name: "Quiche Lorraine",
		description: "Savory quiche with cheese and vegetables.",
		category: "dairy",
		subcategory: "",
		size: [
			{ quantity: 1, price: 8.99 },
			{ quantity: 2, price: 17.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/quiche_lorraine.jpg",
			alt: "Quiche Lorraine",
		},
	},
	{
		name: "Spinach Pie",
		description: "Flaky pastry filled with spinach and cheese.",
		category: "dairy",
		subcategory: "",
		size: [
			{ quantity: 1, price: 7.99 },
			{ quantity: 2, price: 15.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/spinach_pie.jpg",
			alt: "Spinach pie",
		},
	},
	{
		name: "Mac and Cheese",
		description: "Creamy macaroni and cheese.",
		category: "dairy",
		subcategory: "",
		size: [
			{ quantity: 1, price: 6.99 },
			{ quantity: 2, price: 13.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/mac_and_cheese.jpg",
			alt: "Mac and cheese",
		},
	},
	{
		name: "Cheese Pizza",
		description: "Classic cheese pizza with tomato sauce.",
		category: "dairy",
		subcategory: "",
		size: [
			{ quantity: 1, price: 10.99 },
			{ quantity: 2, price: 20.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/cheese_pizza.jpg",
			alt: "Cheese pizza",
		},
	},
	{
		name: "Cheesecake",
		description: "Creamy cheesecake with a graham cracker crust.",
		category: "desserts",
		subcategory: "dairy",
		size: [
			{ quantity: 1, price: 6.99 },
			{ quantity: 2, price: 12.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/cheesecake.jpg",
			alt: "Cheesecake",
		},
	},
	{
		name: "Chocolate Cake",
		description: "Rich chocolate cake, parve and delicious.",
		category: "desserts",
		subcategory: "parve",
		size: [
			{ quantity: 1, price: 5.99 },
			{ quantity: 2, price: 11.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/chocolate_cake.jpg",
			alt: "Chocolate cake",
		},
	},
	{
		name: "Vegan Brownie",
		description: "Fudgy vegan brownie made with cocoa and nuts.",
		category: "desserts",
		subcategory: "vegan",
		size: [
			{ quantity: 1, price: 4.99 },
			{ quantity: 2, price: 9.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_brownie.jpg",
			alt: "Vegan brownie",
		},
	},
	{
		name: "Apple Pie",
		description: "Classic apple pie with cinnamon.",
		category: "desserts",
		subcategory: "parve",
		size: [
			{ quantity: 1, price: 5.49 },
			{ quantity: 2, price: 10.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/apple_pie.jpg",
			alt: "Apple pie",
		},
	},
	{
		name: "Fruit Salad",
		description: "Fresh fruit salad with seasonal fruits.",
		category: "desserts",
		subcategory: "parve",
		size: [
			{ quantity: 1, price: 4.49 },
			{ quantity: 2, price: 8.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/fruit_salad.jpg",
			alt: "Fruit salad",
		},
	},
	{
		name: "Sandwich Platter",
		description: "Assorted sandwich platter for sharing.",
		category: "platters",
		subcategory: "",
		size: [{ quantity: 1, price: 29.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/sandwich_platter.jpg",
			alt: "Sandwich platter",
		},
	},
	{
		name: "Sushi Platter",
		description: "Variety of sushi rolls and nigiri.",
		category: "platters",
		subcategory: "",
		size: [{ quantity: 1, price: 39.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/sushi_platter.jpg",
			alt: "Sushi platter",
		},
	},
	{
		name: "Cheese Platter",
		description: "Assorted cheeses with crackers and fruit.",
		category: "platters",
		subcategory: "",
		size: [{ quantity: 1, price: 34.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/cheese_platter.jpg",
			alt: "Cheese platter",
		},
	},
	{
		name: "Vegetable Platter",
		description: "Fresh cut vegetables with dip.",
		category: "platters",
		subcategory: "",
		size: [{ quantity: 1, price: 24.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegetable_platter.jpg",
			alt: "Vegetable platter",
		},
	},
	{
		name: "Fruit Platter",
		description: "Assorted sliced fresh fruits.",
		category: "platters",
		subcategory: "",
		size: [{ quantity: 1, price: 27.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/fruit_platter.jpg",
			alt: "Fruit platter",
		},
	},
	{
		name: "Greek Salad",
		description: "Fresh Greek salad with feta cheese and olives.",
		category: "salads",
		subcategory: "",
		size: [{ quantity: 1, price: 7.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/greek_salad.jpg",
			alt: "Greek salad",
		},
	},
	{
		name: "Caesar Salad",
		description: "Classic Caesar salad with croutons.",
		category: "salads",
		subcategory: "",
		size: [{ quantity: 1, price: 8.49 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/caesar_salad.jpg",
			alt: "Caesar salad",
		},
	},
	{
		name: "Israeli Salad",
		description: "Chopped cucumber, tomato, and herbs.",
		category: "salads",
		subcategory: "",
		size: [{ quantity: 1, price: 6.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/israeli_salad.jpg",
			alt: "Israeli salad",
		},
	},
	{
		name: "Tabbouleh",
		description: "Parsley, bulgur, tomato, and lemon salad.",
		category: "salads",
		subcategory: "",
		size: [{ quantity: 1, price: 7.49 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/tabbouleh.jpg",
			alt: "Tabbouleh",
		},
	},
	{
		name: "Coleslaw",
		description: "Creamy coleslaw with cabbage and carrots.",
		category: "salads",
		subcategory: "",
		size: [{ quantity: 1, price: 5.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/coleslaw.jpg",
			alt: "Coleslaw",
		},
	},
	{
		name: "French Fries",
		description: "Crispy golden French fries.",
		category: "sides",
		subcategory: "",
		size: [
			{ quantity: 1, price: 3.99 },
			{ quantity: 2, price: 7.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/french_fries.jpg",
			alt: "French fries",
		},
	},
	{
		name: "Mashed Potatoes",
		description: "Creamy mashed potatoes with butter.",
		category: "sides",
		subcategory: "",
		size: [
			{ quantity: 1, price: 4.49 },
			{ quantity: 2, price: 8.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/mashed_potatoes.jpg",
			alt: "Mashed potatoes",
		},
	},
	{
		name: "Rice Pilaf",
		description: "Fluffy rice pilaf with herbs.",
		category: "sides",
		subcategory: "",
		size: [
			{ quantity: 1, price: 3.99 },
			{ quantity: 2, price: 7.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/rice_pilaf.jpg",
			alt: "Rice pilaf",
		},
	},
	{
		name: "Steamed Vegetables",
		description: "Assorted steamed vegetables.",
		category: "sides",
		subcategory: "",
		size: [
			{ quantity: 1, price: 4.99 },
			{ quantity: 2, price: 9.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/steamed_vegetables.jpg",
			alt: "Steamed vegetables",
		},
	},
	{
		name: "Garlic Bread",
		description: "Toasted garlic bread slices.",
		category: "sides",
		subcategory: "",
		size: [
			{ quantity: 1, price: 3.49 },
			{ quantity: 2, price: 6.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/garlic_bread.jpg",
			alt: "Garlic bread",
		},
	},
	{
		name: "Vegan Wrap",
		description: "Tortilla wrap filled with fresh vegan ingredients.",
		category: "vegan",
		subcategory: "",
		size: [{ quantity: 1, price: 6.49 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_wrap.jpg",
			alt: "Vegan wrap",
		},
	},
	{
		name: "Vegan Burger",
		description: "Plant-based burger with lettuce and tomato.",
		category: "vegan",
		subcategory: "",
		size: [{ quantity: 1, price: 7.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_burger.jpg",
			alt: "Vegan burger",
		},
	},
	{
		name: "Vegan Chili",
		description: "Hearty vegan chili with beans and vegetables.",
		category: "vegan",
		subcategory: "",
		size: [{ quantity: 1, price: 6.99 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_chili.jpg",
			alt: "Vegan chili",
		},
	},
	{
		name: "Vegan Sushi",
		description: "Sushi rolls with avocado and cucumber.",
		category: "vegan",
		subcategory: "",
		size: [{ quantity: 1, price: 8.49 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_sushi.jpg",
			alt: "Vegan sushi",
		},
	},
	{
		name: "Vegan Pasta",
		description: "Pasta with tomato sauce and vegetables.",
		category: "vegan",
		subcategory: "",
		size: [{ quantity: 1, price: 7.49 }],
		unit: "יחידות",
		image: {
			url: "https://example.com/images/vegan_pasta.jpg",
			alt: "Vegan pasta",
		},
	},
];
