export const exampleData = [
	{
		name: "Grilled Steak",
		description: "Juicy grilled steak cooked to perfection.",
		category: "meat",
		subCategory: "",
		size: [
			{ quantity: 1, price: 12.99 },
			{ quantity: 2, price: 24.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1639561/pexels-photo-1639561.jpeg",
			alt: "Grilled steak",
		},
	},
	{
		name: "Roast Chicken",
		description: "Tender roast chicken with herbs.",
		category: "meat",
		subCategory: "",
		size: [
			{ quantity: 1, price: 11.99 },
			{ quantity: 2, price: 22.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/265393/pexels-photo-265393.jpeg",
			alt: "Roast chicken",
		},
	},
	{
		name: "Beef Kebab",
		description: "Spiced beef kebabs grilled on skewers.",
		category: "meat",
		subCategory: "",
		size: [
			{ quantity: 1, price: 10.99 },
			{ quantity: 2, price: 21.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
			alt: "Beef kebab",
		},
	},
	{
		name: "Lamb Chops",
		description: "Grilled lamb chops with rosemary.",
		category: "meat",
		subCategory: "",
		size: [
			{ quantity: 1, price: 14.99 },
			{ quantity: 2, price: 28.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/7627486/pexels-photo-7627486.jpeg",
			alt: "Lamb chops",
		},
	},
	{
		name: "Turkey Schnitzel",
		description: "Crispy breaded turkey schnitzel.",
		category: "meat",
		subCategory: "",
		size: [
			{ quantity: 1, price: 9.99 },
			{ quantity: 2, price: 19.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg",
			alt: "Turkey schnitzel",
		},
	},
	{
		name: "Cheese Lasagna",
		description: "Classic Italian lasagna with rich cheese and tomato sauce.",
		category: "dairy",
		subCategory: "",
		size: [
			{ quantity: 1, price: 9.99 },
			{ quantity: 2, price: 18.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/5949902/pexels-photo-5949902.jpeg",
			alt: "Cheese lasagna",
		},
	},
	{
		name: "Quiche Lorraine",
		description: "Savory quiche with cheese and vegetables.",
		category: "dairy",
		subCategory: "",
		size: [
			{ quantity: 1, price: 8.99 },
			{ quantity: 2, price: 17.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/6941010/pexels-photo-6941010.jpeg",
			alt: "Quiche Lorraine",
		},
	},
	{
		name: "Spinach Pie",
		description: "Flaky pastry filled with spinach and cheese.",
		category: "dairy",
		subCategory: "",
		size: [
			{ quantity: 1, price: 7.99 },
			{ quantity: 2, price: 15.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/156114/pexels-photo-156114.jpeg",
			alt: "Spinach pie",
		},
	},
	{
		name: "Mac and Cheese",
		description: "Creamy macaroni and cheese.",
		category: "dairy",
		subCategory: "",
		size: [
			{ quantity: 1, price: 6.99 },
			{ quantity: 2, price: 13.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/803963/pexels-photo-803963.jpeg",
			alt: "Mac and cheese",
		},
	},
	{
		name: "Cheese Pizza",
		description: "Classic cheese pizza with tomato sauce.",
		category: "dairy",
		subCategory: "",
		size: [
			{ quantity: 1, price: 10.99 },
			{ quantity: 2, price: 20.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg",
			alt: "Cheese pizza",
		},
	},
	{
		name: "Cheesecake",
		description: "Creamy cheesecake with a graham cracker crust.",
		category: "desserts",
		subCategory: "dairy",
		size: [
			{ quantity: 1, price: 6.99 },
			{ quantity: 2, price: 12.99 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/704971/pexels-photo-704971.jpeg",
			alt: "Cheesecake",
		},
	},
	{
		name: "Chocolate Cake",
		description: "Rich chocolate cake, parve and delicious.",
		category: "desserts",
		subCategory: "parve",
		size: [
			{ quantity: 1, price: 5.99 },
			{ quantity: 2, price: 11.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/533325/pexels-photo-533325.jpeg",
			alt: "Chocolate cake",
		},
	},
	{
		name: "Vegan Brownie",
		description: "Fudgy vegan brownie made with cocoa and nuts.",
		category: "desserts",
		subCategory: "vegan",
		size: [
			{ quantity: 1, price: 4.99 },
			{ quantity: 2, price: 9.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg",
			alt: "Vegan brownie",
		},
	},
	{
		name: "Apple Pie",
		description: "Classic apple pie with cinnamon.",
		category: "desserts",
		subCategory: "parve",
		size: [
			{ quantity: 1, price: 5.49 },
			{ quantity: 2, price: 10.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/161887/apple-pie-dessert-pastry-161887.jpeg",
			alt: "Apple pie",
		},
	},
	{
		name: "Fruit Salad",
		description: "Fresh fruit salad with seasonal fruits.",
		category: "desserts",
		subCategory: "parve",
		size: [
			{ quantity: 1, price: 4.49 },
			{ quantity: 2, price: 8.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg",
			alt: "Fruit salad",
		},
	},
	{
		name: "Sandwich Platter",
		description: "Assorted sandwich platter for sharing.",
		category: "platters",
		subCategory: "",
		size: [{ quantity: 1, price: 29.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg",
			alt: "Sandwich platter",
		},
	},
	{
		name: "Sushi Platter",
		description: "Variety of sushi rolls and nigiri.",
		category: "platters",
		subCategory: "",
		size: [{ quantity: 1, price: 39.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg",
			alt: "Sushi platter",
		},
	},
	{
		name: "Cheese Platter",
		description: "Assorted cheeses with crackers and fruit.",
		category: "platters",
		subCategory: "",
		size: [{ quantity: 1, price: 34.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/416471/pexels-photo-416471.jpeg",
			alt: "Cheese platter",
		},
	},
	{
		name: "Vegetable Platter",
		description: "Fresh cut vegetables with dip.",
		category: "platters",
		subCategory: "",
		size: [{ quantity: 1, price: 24.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg",
			alt: "Vegetable platter",
		},
	},
	{
		name: "Fruit Platter",
		description: "Assorted sliced fresh fruits.",
		category: "platters",
		subCategory: "",
		size: [{ quantity: 1, price: 27.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg",
			alt: "Fruit platter",
		},
	},
	{
		name: "Greek Salad",
		description: "Fresh Greek salad with feta cheese and olives.",
		category: "salads",
		subCategory: "",
		size: [{ quantity: 1, price: 7.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg",
			alt: "Greek salad",
		},
	},
	{
		name: "Caesar Salad",
		description: "Classic Caesar salad with croutons.",
		category: "salads",
		subCategory: "",
		size: [{ quantity: 1, price: 8.49 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg",
			alt: "Caesar salad",
		},
	},
	{
		name: "Israeli Salad",
		description: "Chopped cucumber, tomato, and herbs.",
		category: "salads",
		subCategory: "",
		size: [{ quantity: 1, price: 6.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/5938/food-salad-healthy-lunch.jpg",
			alt: "Israeli salad",
		},
	},
	{
		name: "Tabbouleh",
		description: "Parsley, bulgur, tomato, and lemon salad.",
		category: "salads",
		subCategory: "",
		size: [{ quantity: 1, price: 7.49 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/7656553/pexels-photo-7656553.jpeg",
			alt: "Tabbouleh",
		},
	},
	{
		name: "Coleslaw",
		description: "Creamy coleslaw with cabbage and carrots.",
		category: "salads",
		subCategory: "",
		size: [{ quantity: 1, price: 5.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/161519/coleslaw-cabbage-salad-food-161519.jpeg",
			alt: "Coleslaw",
		},
	},
	{
		name: "French Fries",
		description: "Crispy golden French fries.",
		category: "sides",
		subCategory: "",
		size: [
			{ quantity: 1, price: 3.99 },
			{ quantity: 2, price: 7.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg",
			alt: "French fries",
		},
	},
	{
		name: "Mashed Potatoes",
		description: "Creamy mashed potatoes with butter.",
		category: "sides",
		subCategory: "",
		size: [
			{ quantity: 1, price: 4.49 },
			{ quantity: 2, price: 8.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg",
			alt: "Mashed potatoes",
		},
	},
	{
		name: "Rice Pilaf",
		description: "Fluffy rice pilaf with herbs.",
		category: "sides",
		subCategory: "",
		size: [
			{ quantity: 1, price: 3.99 },
			{ quantity: 2, price: 7.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
			alt: "Rice pilaf",
		},
	},
	{
		name: "Steamed Vegetables",
		description: "Assorted steamed vegetables.",
		category: "sides",
		subCategory: "",
		size: [
			{ quantity: 1, price: 4.99 },
			{ quantity: 2, price: 9.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/539431/pexels-photo-539431.jpeg",
			alt: "Steamed vegetables",
		},
	},
	{
		name: "Garlic Bread",
		description: "Toasted garlic bread slices.",
		category: "sides",
		subCategory: "",
		size: [
			{ quantity: 1, price: 3.49 },
			{ quantity: 2, price: 6.49 },
		],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg",
			alt: "Garlic bread",
		},
	},
	{
		name: "Vegan Wrap",
		description: "Tortilla wrap filled with fresh vegan ingredients.",
		category: "vegan",
		subCategory: "",
		size: [{ quantity: 1, price: 6.49 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/5945640/pexels-photo-5945640.jpeg",
			alt: "Vegan wrap",
		},
	},
	{
		name: "Vegan Burger",
		description: "Plant-based burger with lettuce and tomato.",
		category: "vegan",
		subCategory: "",
		size: [{ quantity: 1, price: 7.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg",
			alt: "Vegan burger",
		},
	},
	{
		name: "Vegan Chili",
		description: "Hearty vegan chili with beans and vegetables.",
		category: "vegan",
		subCategory: "",
		size: [{ quantity: 1, price: 6.99 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/5737377/pexels-photo-5737377.jpeg",
			alt: "Vegan chili",
		},
	},
	{
		name: "Vegan Sushi",
		description: "Sushi rolls with avocado and cucumber.",
		category: "vegan",
		subCategory: "",
		size: [{ quantity: 1, price: 8.49 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/884596/pexels-photo-884596.jpeg",
			alt: "Vegan sushi",
		},
	},
	{
		name: "Vegan Pasta",
		description: "Pasta with tomato sauce and vegetables.",
		category: "vegan",
		subCategory: "",
		size: [{ quantity: 1, price: 7.49 }],
		unit: "יחידות",
		image: {
			url: "https://images.pexels.com/photos/1487511/pexels-photo-1487511.jpeg",
			alt: "Vegan pasta",
		},
	},
];
